const Template = {

    build(location) {

        return `#!url=https://raw.githubusercontent.com/hoicau/ios-location-spoofer/refs/heads/main/scripts/ios-location-spoofer.sgmodule
#!name=iOS Location Spoofer
#!desc=Generated by Location Generator iOS
#!homepage=https://github.com

[Script]

iOS Location Spoofer = type=http-response,pattern=^https?://(?:gs-loc(?:-cn)?.apple.com|bluedot.is.autonavi.com(?:.gds.alibabadns.com)?)/clls/wloc(?:\\?.*)?$,requires-body=1,binary-body-mode=1,max-size=1048576,timeout=10,script-path=https://raw.githubusercontent.com/hoicau/ios-location-spoofer/main/scripts/location-spoofer.js,argument=mode=response&latitude=${location.lat}&longitude=${location.lon}&horizontalAccuracy=39&verticalAccuracy=1000&altitude=530&debug=false

[MITM]

hostname = %APPEND% gs-loc.apple.com, gs-loc-cn.apple.com, bluedot.is.autonavi.com, bluedot.is.autonavi.com.gds.alibabadns.com`;
    }

};
